version: "3"

services:
  api_server:
    build: ./api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/usr/src/app
    environment:
      - ROCKET_ENV=prod
    command: bash -c "cargo watch --poll -x run"
