[package]
name = "h3e"
version = "0.1.0"
authors = ["Andrew O'Reilly-Nugent <aornugent@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
libh3 = "0.1.8"
libh3-sys = "0.1.3"
rocket = "0.5.0-rc.2"

[build-dependencies]
cmake = "0.1"
